[env]
TERM = "xterm-256color"
ttymouse = "sgr"

[font]
normal = { family = "Roboto Mono" }
size = 10

[keyboard]
bindings = [
  # xterm-style (\e[27;<modifier>;<keycode>~) and libtickit-style (\e[<keycode>;<modifier>u)
  # https://github.com/alacritty/alacritty/issues/2049
  # { mods = "Control", key = "Space", chars = "\u001b[27;5;32~" },
  { mods = "Control", key = "Space", chars = "\u001b[emacs-C-SPC" },
  { mods = "Control", key = "Period", chars = "\u001b[emacs-C-." },
  { mods = "Control", key = "Comma", chars = "\u001b[emacs-C-," },
  { mods = "Control", key = "/", chars = "\u001b[emacs-C-/" },
]